### ISSUE TITLE
Ouline high level package structure in the `extracted_info.py` file

### ISSUE THREAD

**Issue by theomnipanda** [paper-parser/paper-parser#2]
So far our package structure is not clear. I am currently working on building a class structure that will comprise the components that each of us are currently working on;
    - Neel: extracting sentences relevant to synthesis
    - Christine: parsing synthesis sentences for procedures and parameters
    - Linnette: ordering steps

**Comment by christinehc** [comment]
Thanks for the outline.  I'll update (in my branch) later how I'm using that template to implement that in my py files.  Still mostly working out of a notebook for troubleshooting reasons.

**Comment by theomnipanda** [comment]
I have made some serious updates to the class 'ExtractSynthesisPerformance' inside the file 'extracted_info.py'. I would appreciate some feedback on it because it assumes output from what each of you are currently working on.

**Comment by christinehc** [comment]
No particular feedback (based on the current state of my function(s)), other than my function currently outputs a list of dictionaries rather than a dictionary by itself.  Might make indexing a little finicky.  Example of current form of output:

`[{'spin_coat': [{'spds': [{'spdvalue': '1,000'}, {'spdvalue': '5,000'}],
    'times': [{'timevalue': '10'}, {'timevalue': '20'}]}]}]`

(hopefully this makes sense)
